[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pyxis = "Ge8XrfHuQwaojtg6DYGZrmU4gadKXtEqwXrEETU7sqfd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./target/deploy/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
